import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'UZ' | 'RU' | 'EN';

const translations: Record<Language, Record<string, string>> = {
  UZ: {
    // Navigation & Header
    'nav.home': 'Bosh sahifa',
    'nav.phones': 'Telefonlar',
    'nav.brands': 'Brendlar',
    'nav.compare': 'Taqqoslash',
    'nav.deals': 'Chegirmalar',
    'nav.about': 'Biz haqimizda',
    'nav.wishlist': 'Sevimlilar',
    'nav.cart': 'Savatcha',
    'nav.orders': 'Buyurtmalarim',
    'nav.profile': 'Profil va sozlamalar',
    'nav.signin': 'Kirish',
    'nav.signup': 'Ro‘yxatdan o‘tish',
    'nav.signout': 'Chiqish',
    'nav.adminPanel': 'Admin Panel',
    'nav.adminControl': 'Boshqaruv paneli',
    'nav.searchPlaceholder': 'Smartfon, brend yoki xususiyat qidiring...',
    'nav.searchShort': 'Telefon qidirish...',
    'nav.welcome': 'NOVA MOBILE ga xush kelibsiz',
    'nav.welcomeSub': 'Buyurtmalarni kuzatish va qurilmalarni saqlash uchun tizimga kiring.',
    'nav.signedInAs': 'Foydalanuvchi',
    'nav.storeAdmin': 'Administrator',
    'nav.vipCustomer': 'VIP Mijoz',
    'nav.flagshipStudio': 'Flagman Studiyasi',

    // Hero Section
    'hero.badge': 'Yangi avlod flagmanlari • Rasmiy kafolat',
    'hero.title1': 'KELAJAK',
    'hero.title2': 'QO‘LINGIZDA.',
    'hero.subtitle': 'Eng kuchli flagman smartfonlarni kashf eting — sun’iy intellekt unumdorligi, professional kamera tizimi va kelajak texnologiyasi bir joyda.',
    'hero.exploreBtn': 'Smartfonlarni ko‘rish',
    'hero.dealsBtn': 'Chegirmalarni ko‘rish',
    'hero.stat1Label': 'Original Qurilmalar',
    'hero.stat2Label': 'Tezkor Yetkazish',
    'hero.stat3Label': 'Rasmiy Kafolat',
    'hero.stat3Val': '1 Yil',
    'hero.chipAi': 'AI QUVVAT',
    'hero.chipAiSub': 'Neyron protsessor',
    'hero.chipCamera': 'PRO KAMERA',
    'hero.chipCameraSub': '200MP Optik zum',
    'hero.chipDisplay': '120Hz EKRAN',
    'hero.chipDisplaySub': 'LTPO OLED Yorqinlik',
    'hero.chipBattery': 'KUN BO‘YI QUVVAT',
    'hero.chipBatterySub': '100W Super Quvvatlash',
    'hero.StartingAt': 'Boshlang‘ich narx',
    'hero.viewDevice': 'Batafsil ko‘rish',

    // Trust Section
    'trust.warrantyTitle': '1 Yillik Rasmiy Kafolat',
    'trust.warrantyDesc': 'Barcha smartfonlar 100% original va rasmiy servis kafolati bilan ta’minlangan.',
    'trust.deliveryTitle': 'Tezkor Yetkazib Berish',
    'trust.deliveryDesc': 'O‘zbekiston bo‘ylab xavfsiz va sug‘urtalangan kuryerlik xizmati.',
    'trust.originalTitle': '100% Original Mahsulot',
    'trust.originalDesc': 'To‘g‘ridan-to‘g‘ri rasmiy ishlab chiqaruvchilardan muhrlangan qutida.',
    'trust.installmentTitle': 'Muddatli To‘lov (0%)',
    'trust.installmentDesc': '12 oygacha bo‘lib to‘lash imkoniyati — ortiqcha foizlarsiz.',
    'trust.supportTitle': '24/7 Ekspert Yordami',
    'trust.supportDesc': 'Texnik mutaxassislarimiz har qanday savolingizga javob berishga tayyor.',

    // Home Sections
    'home.brandsBadge': 'Rasmiy Hamkorlar',
    'home.brandsTitle': 'Brend bo‘yicha tanlang',
    'home.brandsSub': 'Dunyo yetakchi texnologiya gigantlarining original smartfonlari',
    'home.viewAllBrands': 'Barcha brendlarni ko‘rish',
    'home.modelsCount': 'modellar',
    'home.featuredBadge': 'Flagmanlar Kolleksiyasi',
    'home.featuredTitle': 'Tavsiya Etilgan Smartfonlar',
    'home.viewAll': 'Barchasini ko‘rish',
    'home.flashBadge': 'Cheklangan Vaqt Taklifi',
    'home.flashTitle': 'Qaynoq Chegirmalar va Aksiyalar',
    'home.flashSub': 'Maxsus narxlardagi flagman smartfonlarni qo‘ldan boy bermang.',
    'home.hours': 'SOAT',
    'home.mins': 'DAQ',
    'home.secs': 'SON',
    'home.bestSellersBadge': 'Mijozlar Tanlovi',
    'home.bestSellersTitle': 'Eng Ko‘p Sotilganlar',
    'home.newArrivalsBadge': 'Yangi Taqdimot',
    'home.newArrivalsTitle': 'Yangi Kelgan Smartfonlar',
    'home.recentBadge': 'Siz Ko‘rgan Qurilmalar',
    'home.recentTitle': 'Yaqinda Ko‘rilgan va Tavsiyalar',
    'home.newsletterBadge': 'VIP Klubga Qo‘shiling',
    'home.newsletterTitle': 'Maxsus chegirmalar va yangi flagmanlar haqida birinchi bo‘lib biling',
    'home.newsletterSub': 'Elektron pochtangizni qoldiring va birinchi xaridingiz uchun maxsus promo-kodga ega bo‘ling.',
    'home.newsletterPlaceholder': 'Email manzilingizni kiriting...',
    'home.newsletterBtn': 'Obuna bo‘lish',
    'home.newsletterSuccess': 'Tabriklaymiz! Siz NOVA VIP xabarnomasiga muvaffaqiyatli obuna bo‘ldingiz.',

    // Product Card & Common Actions
    'product.inStock': 'Mavjud',
    'product.lowStock': 'Kam qolgan',
    'product.outOfStock': 'Tugagan',
    'product.left': 'dona qoldi',
    'product.addToCart': 'Savatchaga',
    'product.addedToCart': 'Savatchaga qo‘shildi',
    'product.buyNow': 'Hozir xarid qilish',
    'product.viewDetails': 'Batafsil',
    'product.compare': 'Taqqoslash',
    'product.wishlist': 'Sevimlilar',
    'product.reviews': 'sharhlar',
    'product.save': 'Tejang',
    'product.hotDeal': 'CHEGIRMA',
    'product.new': 'YANGI',
    'product.bestSeller': 'XIT SOTUV',
    'product.retry': 'Qayta urinish',
    'product.errorLoading': 'Ma’lumotni yuklab bo‘lmadi.',

    // Catalog / Phones Page
    'catalog.badge': 'NOVA Katalogi',
    'catalog.title': 'Mukammal smartfoningizni toping',
    'catalog.subtitle': 'Kuchli filtrlar yordamida o‘zingizga mos flagman qurilmani tanlang',
    'catalog.filters': 'Filtrlash',
    'catalog.clearAll': 'Tozalash',
    'catalog.showing': 'Ko‘rsatilmoqda',
    'catalog.devices': 'ta smartfon',
    'catalog.sortBy': 'Saralash:',
    'catalog.sortPopular': 'Eng ommabop',
    'catalog.sortNewest': 'Yangi kelganlar',
    'catalog.sortPriceAsc': 'Narx: Arzondan qimmatga',
    'catalog.sortPriceDesc': 'Narx: Qimmatdan arzonga',
    'catalog.sortRating': 'Yuqori reytingli',
    'catalog.brand': 'Brend',
    'catalog.priceRange': 'Narx oralig‘i',
    'catalog.ram': 'Tezkor xotira (RAM)',
    'catalog.storage': 'Doimiy xotira',
    'catalog.camera': 'Asosiy kamera',
    'catalog.battery': 'Batareya sig‘imi',
    'catalog.display': 'Displey turi',
    'catalog.refreshRate': 'Yangilanish chastotasi',
    'catalog.os': 'Operatsion tizim',
    'catalog.rating': 'Minimal reyting',
    'catalog.availability': 'Mavjudligi',
    'catalog.inStockOnly': 'Faqat sotuvda borlari',
    'catalog.noResults': 'Mahsulotlar topilmadi.',
    'catalog.noResultsSub': 'Qidiruv so‘zini yoki filtrlarni o‘zgartirib ko‘ring.',
    'catalog.resetFilters': 'Filtrlarni tiklash',
    'catalog.all': 'Barchasi',

    // Product Detail Page
    'detail.backToCatalog': 'Katalogga qaytish',
    'detail.color': 'Ranglar',
    'detail.storage': 'Doimiy xotira',
    'detail.ram': 'Tezkor xotira',
    'detail.installment': 'Muddatli to‘lov:',
    'detail.perMonth': '/ oyiga (12 oy)',
    'detail.deliveryInfo': 'Toshkent bo‘ylab 2 soatda, viloyatlarga 24 soat ichida bepul yetkazib berish',
    'detail.warrantyInfo': '1 yil rasmiy kafolat + 14 kun ichida qaytarish imkoniyati',
    'detail.tabOverview': 'Tavsif',
    'detail.tabSpecs': 'Texnik xususiyatlar',
    'detail.tabCamera': 'Kamera',
    'detail.tabBattery': 'Batareya va Displey',
    'detail.tabReviews': 'Sharhlar',
    'detail.specDisplay': 'Displey',
    'detail.specProcessor': 'Protsessor',
    'detail.specRam': 'Tezkor xotira',
    'detail.specStorage': 'Doimiy xotira',
    'detail.specMainCam': 'Kamera',
    'detail.specFrontCam': 'Old kamera',
    'detail.specBattery': 'Batareya',
    'detail.specCharging': 'Quvvatlash',
    'detail.specRefresh': 'Ekran chastotasi',
    'detail.specOs': 'Operatsion tizim',
    'detail.specWeight': 'Vazni',
    'detail.specDimensions': 'O‘lchamlari',
    'detail.writeReview': 'Sharh qoldirish',
    'detail.yourRating': 'Reyting',
    'detail.reviewTitle': 'Sarlavha',
    'detail.reviewComment': 'Sharh',
    'detail.reviewPros': 'Afzalliklari',
    'detail.reviewCons': 'Kamchiliklari',
    'detail.submitReview': 'Sharhni yuborish',
    'detail.relatedTitle': 'O‘xshash Flagmanlar',
    'detail.notFound': 'Mahsulotlar topilmadi.',

    // Brands Page
    'brands.title': 'Rasmiy Brendlar va Hamkorlar',
    'brands.subtitle': 'NOVA MOBILE barcha yetakchi jahon brendlarining rasmiy vakili hisoblanadi. Har bir qurilma original va kafolatlangan.',
    'brands.exploreModels': 'Modellarni ko‘rish',

    // Deals Page
    'deals.badge': 'Maxsus Chegirmalar',
    'deals.title': 'Qaynoq Chegirmalar va Flagman Aksiyalar',
    'deals.subtitle': 'Eng so‘nggi smartfonlarni maxsus chegirmali narxlarda xarid qiling. Takliflar soni cheklangan.',

    // Compare Page
    'compare.title': 'Smartfonlarni Taqqoslash',
    'compare.subtitle': '3 tagacha smartfonni yonma-yon texnik xususiyatlari bo‘yicha solishtiring',
    'compare.emptyTitle': 'Taqqoslash ro‘yxati bo‘sh',
    'compare.emptySub': 'Smartfonlarni solishtirish uchun katalogdan kamida 2 ta modelni qo‘shing.',
    'compare.browsePhones': 'Smartfonlarni tanlash',
    'compare.clearAll': 'Ro‘yxatni tozalash',
    'compare.addDevice': 'Smartfon qo‘shish',
    'compare.parameter': 'Xususiyat',
    'compare.price': 'Narx',
    'compare.rating': 'Reyting',

    // Wishlist Page
    'wishlist.title': 'Sevimli Smartfonlar',
    'wishlist.subtitle': 'Siz saqlab qo‘ygan flagman qurilmalar ro‘yxati',
    'wishlist.emptyTitle': 'Sevimlilar ro‘yxati bo‘sh',
    'wishlist.emptySub': 'Yoqtirgan smartfonlaringizni keyinroq ko‘rish uchun yurakcha tugmasini bosing.',
    'wishlist.moveAllToCart': 'Barchasini savatchaga qo‘shish',

    // Cart & Quick Cart Drawer
    'cart.title': 'Xarid Savatchasi',
    'cart.emptyTitle': 'Savatchangiz hozircha bo‘sh',
    'cart.emptySub': 'Katalogimizdan o‘zingizga mos flagman smartfonni tanlang va savatchaga qo‘shing.',
    'cart.continueShopping': 'Xaridni davom ettirish',
    'cart.orderSummary': 'Buyurtma xulosasi',
    'cart.subtotal': 'Mahsulotlar narxi',
    'cart.discount': 'Chegirma',
    'cart.shipping': 'Yetkazib berish',
    'cart.free': 'Bepul',
    'cart.tax': 'Soliq va yig‘imlar (0%)',
    'cart.total': 'Jami summa',
    'cart.promoPlaceholder': 'Promo-kod kiriting (masalan: NOVA10)',
    'cart.apply': 'Qo‘llash',
    'cart.checkoutBtn': 'Rasmiylashtirishga o‘tish',
    'cart.viewCart': 'Savatchani ochish',
    'cart.clearCart': 'Savatchani tozalash',

    // Checkout Page
    'checkout.title': 'Buyurtmani Rasmiylashtirish',
    'checkout.subtitle': 'Ma’lumotlaringizni kiriting va to‘lov turini tanlang',
    'checkout.step1': '1. Shaxsiy ma’lumotlar',
    'checkout.step2': '2. Yetkazib berish manzili',
    'checkout.step3': '3. To‘lov usuli',
    'checkout.fullName': 'To‘liq ismingiz (F.I.Sh)',
    'checkout.phone': 'Telefon raqamingiz',
    'checkout.email': 'Elektron pochta',
    'checkout.deliveryMethod': 'Yetkazib berish turi',
    'checkout.standardDelivery': 'Standart kuryer (Bepul • 24 soat ichida)',
    'checkout.expressDelivery': 'VIP Ekspress (2 soat ichida • $15)',
    'checkout.storePickup': 'Do‘kondan olib ketish (Bepul • Toshkent City)',
    'checkout.region': 'Viloyat / Hudud',
    'checkout.city': 'Shahar / Tuman',
    'checkout.address': 'Manzil (ko‘cha, uy, xonadon)',
    'checkout.notes': 'Kuryer uchun izoh (ixtiyoriy)',
    'checkout.payCard': 'Bank kartasi (Uzcard / Humo / Visa / MasterCard)',
    'checkout.payPayme': 'Payme / Click / Uzum Pay',
    'checkout.payCash': 'Yetkazib berilganda naqd pul yoki terminal orqali',
    'checkout.payInstallment': 'Muddatli to‘lov (12 oy • 0% boshlang‘ich to‘lov)',
    'checkout.placeOrder': 'Buyurtmani tasdiqlash',
    'checkout.processing': 'Ma’lumot yuklanmoqda...',

    // Order Success & Orders Page
    'success.badge': 'Muvaffaqiyatli Xarid',
    'success.title': 'BUYURTMANGIZ QABUL QILINDI',
    'success.subtitle': 'Xaridingiz uchun rahmat! Operatorimiz tez orada siz bilan bog‘lanib, yetkazib berish vaqtini tasdiqlaydi.',
    'success.orderId': 'Buyurtma raqami',
    'success.status': 'Holati',
    'success.payment': 'To‘lov',
    'success.totalPaid': 'Jami summa',
    'success.viewOrders': 'Buyurtmalarimni ko‘rish',
    'success.backHome': 'Bosh sahifaga qaytish',
    'orders.title': 'Buyurtmalar Tarixi',
    'orders.subtitle': 'Barcha xarid qilingan qurilmalar va yetkazib berish holatini kuzating',
    'orders.emptyTitle': 'Buyurtmalar topilmadi.',
    'orders.emptySub': 'Birinchi flagman smartfoningizni bugun buyurtma qiling.',

    // Profile & Auth Pages (/signin, /signup, /profile)
    'auth.signInTitle': 'Tizimga kirish',
    'auth.signUpTitle': 'Ro‘yxatdan o‘tish',
    'auth.subtitle': 'Buyurtmalar tarixi, saqlangan qurilmalar va VIP imtiyozlardan foydalaning.',
    'auth.signInTab': 'Kirish',
    'auth.signUpTab': 'Ro‘yxatdan o‘tish',
    'auth.adminPanelTab': 'Admin Panel',
    'auth.adminLoginLink': 'Admin kirish',
    'auth.fullName': 'To‘liq ism',
    'auth.email': 'Elektron pochta',
    'auth.phone': 'Telefon raqami',
    'auth.password': 'Parol',
    'auth.confirmPassword': 'Parolni tasdiqlash',
    'auth.showPassword': 'Parolni ko‘rsatish',
    'auth.hidePassword': 'Parolni yashirish',
    'auth.signInBtn': 'Kirish',
    'auth.signUpBtn': 'Ro‘yxatdan o‘tish',
    'auth.passwordMismatch': 'Parollar bir-biriga mos kelmadi!',
    'auth.passwordTooShort': 'Parol kamida 6 ta belgidan iborat bo‘lishi kerak!',
    'auth.fillRequired': 'Barcha majburiy maydonlarni to‘ldiring!',
    'auth.welcomeBack': 'NOVA MOBILE ga xush kelibsiz!',
    'auth.accountCreated': 'Hisobingiz muvaffaqiyatli yaratildi!',
    'auth.demoProfiles': 'Tezkor Demo Hisoblar',
    'auth.customerDemo': 'Mijoz Profili',
    'auth.savedDelivery': 'Yetkazib berish ma’lumotlari',
    'auth.savedWishlist': 'Saqlangan sevimlilar',
    'auth.editProfileTitle': 'Shaxsiy va yetkazib berish ma’lumotlarini tahrirlash',
    'auth.saveChanges': 'Saqlash',
    'auth.profileUpdated': 'Profil ma’lumotlari saqlandi!',

    // About Page
    'about.badge': 'NOVA MOBILE Haqida',
    'about.title': 'O‘zbekistondagi №1 Premium Flagman Smartfonlar Studiyasi',
    'about.subtitle': 'Biz mijozlarimizga faqat 100% original, rasmiy kafolatga ega eng so‘nggi jahon flagmanlarini taqdim etamiz.',
    'about.missionTitle': 'Bizning Missiyamiz',
    'about.missionDesc': 'Har bir mijozga jahon darajasidagi xarid tajribasi, shaffof narxlar va ishonchli rasmiy servis xizmatini taqdim etish.',

    // Footer
    'footer.desc': 'Kelajak texnologiyalari va original flagman smartfonlarning rasmiy onlayn do‘koni. 1 yillik kafolat va tezkor yetkazib berish.',
    'footer.shop': 'Katalog',
    'footer.company': 'Kompaniya',
    'footer.support': 'Mijozlar xizmati',
    'footer.contact': 'Bog‘lanish',
    'footer.rights': 'Barcha huquqlar himoyalangan.',
    'footer.address': 'Toshkent sh., Shayxontohur tumani, Tashkent City, Boulevard, 14-uy',
    'footer.hours': 'Ish vaqti: Har kuni 09:00 — 22:00',

    // ==================================================
    // ADMIN PANEL TRANSLATIONS (UZ)
    // ==================================================
    // Sidebar & Layout
    'admin.sidebar.control': 'Boshqaruv',
    'admin.sidebar.dashboard': 'Bosh sahifa',
    'admin.sidebar.products': 'Mahsulotlar',
    'admin.sidebar.orders': 'Buyurtmalar',
    'admin.sidebar.customers': 'Mijozlar',
    'admin.sidebar.users': 'Foydalanuvchilar',
    'admin.sidebar.brands': 'Brendlar',
    'admin.sidebar.categories': 'Kategoriyalar',
    'admin.sidebar.inventory': 'Ombor',
    'admin.sidebar.deals': 'Chegirmalar',
    'admin.sidebar.reviews': 'Sharhlar',
    'admin.sidebar.banners': 'Bannerlar',
    'admin.sidebar.analytics': 'Tahlil',
    'admin.sidebar.notifications': 'Bildirishnomalar',
    'admin.sidebar.settings': 'Sozlamalar',
    'admin.sidebar.profile': 'Admin profili',
    'admin.sidebar.logout': 'Chiqish',
    'admin.sidebar.liveStore': 'Do‘konga o‘tish',

    // Admin Login
    'admin.login.title': 'Admin kirish',
    'admin.login.subtitle': 'NOVA MOBILE boshqaruv tizimiga xavfsiz kirish',
    'admin.login.email': 'Elektron pochta',
    'admin.login.password': 'Parol',
    'admin.login.forgotPassword': 'Parolni unutdingizmi?',
    'admin.login.rememberMe': 'Eslab qolish',
    'admin.login.encryptedSession': 'Himoyalangan JWT sessiya',
    'admin.login.submit': 'Kirish',
    'admin.login.verifying': 'Tekshirilmoqda...',
    'admin.login.returnStore': 'Do‘konga qaytish',
    'admin.login.resetTitle': 'Admin parolini tiklash',
    'admin.login.resetDesc': 'Ro‘yxatdan o‘tgan administrator elektron pochtasini kiriting yoki serverdagi ADMIN_PASSWORD o‘zgaruvchisini yangilang.',
    'admin.login.sendRecovery': 'Tiklash yo‘riqnomasini yuborish',
    'admin.login.recoverySent': 'Tiklash yo‘riqnomasi administrator pochtasiga yuborildi.',
    'admin.login.accessDenied': 'Kirish rad etildi: Faqat administratorlar uchun.',

    // Dashboard
    'admin.dashboard.title': 'Bosh sahifa',
    'admin.dashboard.subtitle': 'Do‘kon ko‘rsatkichlari, savdo oqimi va ombor holati bo‘yicha umumiy ma’lumot',
    'admin.dashboard.totalRevenue': 'Umumiy daromad',
    'admin.dashboard.totalOrders': 'Jami buyurtmalar',
    'admin.dashboard.totalProducts': 'Jami mahsulotlar',
    'admin.dashboard.totalCustomers': 'Jami mijozlar',
    'admin.dashboard.pendingOrders': 'Kutilayotgan buyurtmalar',
    'admin.dashboard.completedOrders': 'Yakunlangan buyurtmalar',
    'admin.dashboard.lowStock': 'Kam qolgan mahsulotlar',
    'admin.dashboard.avgOrderValue': 'O‘rtacha buyurtma qiymati',
    'admin.dashboard.revenueGrowth': '+14.8% o‘tgan davrga nisbatan',
    'admin.dashboard.fulfillmentRate': '98.6% bajarilish ko‘rsatkichi',
    'admin.dashboard.acrossBrands': 'Rasmiy brendlar bo‘yicha',
    'admin.dashboard.activeProfiles': 'Faol tasdiqlangan mijozlar',
    'admin.dashboard.recentOrders': 'So‘nggi buyurtmalar',
    'admin.dashboard.allOrders': 'Barcha buyurtmalar',
    'admin.dashboard.restock': 'Zaxirani to‘ldirish',
    'admin.dashboard.allStocked': 'Barcha mahsulotlar yetarli miqdorda mavjud.',
    'admin.dashboard.unitsRemaining': 'dona qoldi',

    // Charts & Date filters
    'admin.chart.revenue': 'Daromad',
    'admin.chart.orders': 'Buyurtmalar',
    'admin.chart.productsSold': 'Sotilgan mahsulotlar',
    'admin.chart.customerGrowth': 'Mijozlar o‘sishi',
    'admin.date.today': 'Bugun',
    'admin.date.7d': '7 kun',
    'admin.date.30d': '30 kun',
    'admin.date.3m': '3 oy',
    'admin.date.12m': '12 oy',

    // Common Buttons & Actions
    'admin.btn.save': 'Saqlash',
    'admin.btn.cancel': 'Bekor qilish',
    'admin.btn.update': 'Yangilash',
    'admin.btn.confirm': 'Tasdiqlash',
    'admin.btn.delete': 'O‘chirish',
    'admin.btn.edit': 'Tahrirlash',
    'admin.btn.view': 'Ko‘rish',
    'admin.btn.duplicate': 'Nusxalash',
    'admin.btn.search': 'Qidirish',
    'admin.btn.filter': 'Filtrlash',
    'admin.btn.sort': 'Saralash',
    'admin.btn.close': 'Yopish',
    'admin.btn.actions': 'Amallar',

    // Products
    'admin.products.title': 'Mahsulotlar',
    'admin.products.subtitle': 'Smartfonlar katalogini boshqarish, yangi mahsulot qo‘shish va narxlarni yangilash',
    'admin.products.addNew': 'Yangi mahsulot qo‘shish',
    'admin.products.editProduct': 'Tahrirlash',
    'admin.products.deleteConfirmTitle': 'Mahsulotni o‘chirishni tasdiqlaysizmi?',
    'admin.products.deleteConfirmDesc': 'Ushbu mahsulot ma’lumotlar bazasi va mijozlar katalogidan butunlay o‘chiriladi:',
    'admin.products.searchPlaceholder': 'Mahsulot nomi, brend yoki SKU bo‘yicha qidirish...',
    'admin.products.name': 'Mahsulot nomi',
    'admin.products.brand': 'Brend',
    'admin.products.category': 'Kategoriya',
    'admin.products.description': 'Tavsif',
    'admin.products.price': 'Narx',
    'admin.products.oldPrice': 'Eski narx',
    'admin.products.discount': 'Chegirma',
    'admin.products.stock': 'Ombordagi soni',
    'admin.products.sku': 'SKU',
    'admin.products.ram': 'Tezkor xotira',
    'admin.products.storage': 'Doimiy xotira',
    'admin.products.processor': 'Protsessor',
    'admin.products.display': 'Displey',
    'admin.products.camera': 'Kamera',
    'admin.products.battery': 'Batareya',
    'admin.products.os': 'Operatsion tizim',
    'admin.products.colors': 'Ranglar',
    'admin.products.images': 'Rasmlar',
    'admin.products.uploadImage': 'Rasm yuklash',
    'admin.products.imagePlaceholder': 'Rasm havolasini (URL) kiriting yoki fayl yuklang...',
    'admin.products.selectBrand': 'Brendni tanlang...',
    'admin.products.selectCategory': 'Kategoriyani tanlang...',
    'admin.products.featured': 'Asosiy mahsulot',
    'admin.products.bestSeller': 'Eng ko‘p sotilgan',
    'admin.products.newArrival': 'Yangi mahsulot',
    'admin.products.deal': 'Chegirma mahsuloti',
    'admin.products.units': 'dona',
    // Validation Errors
    'admin.products.errName': 'Mahsulot nomini kiriting.',
    'admin.products.errBrand': 'Brendni tanlang.',
    'admin.products.errCategory': 'Kategoriya tanlang.',
    'admin.products.errPrice': 'Narxni kiriting.',
    'admin.products.errStock': 'Ombordagi sonini kiriting.',
    'admin.products.errImage': 'Rasm yuklang.',

    // Categories
    'admin.categories.title': 'Kategoriyalar',
    'admin.categories.subtitle': 'Smartfonlarni toifalar bo‘yicha guruhlash va boshqarish',
    'admin.categories.add': 'Kategoriya qo‘shish',
    'admin.categories.edit': 'Kategoriyani tahrirlash',
    'admin.categories.delete': 'Kategoriyani o‘chirish',
    'admin.categories.productCount': 'Mahsulotlar soni',
    'admin.categories.name': 'Kategoriya nomi',

    // Brands
    'admin.brands.title': 'Brendlar',
    'admin.brands.subtitle': 'Rasmiy smartfon ishlab chiqaruvchilari va hamkor brendlar ro‘yxati',
    'admin.brands.add': 'Brend qo‘shish',
    'admin.brands.edit': 'Brendni tahrirlash',
    'admin.brands.delete': 'Brendni o‘chirish',
    'admin.brands.name': 'Brend nomi',
    'admin.brands.logo': 'Logotip',
    'admin.brands.description': 'Tavsif',
    'admin.brands.status': 'Holati',

    // Orders
    'admin.orders.title': 'Buyurtmalar',
    'admin.orders.subtitle': 'Mijozlar buyurtmalarini ko‘rib chiqish, yetkazib berish va holatini boshqarish',
    'admin.orders.orderNumber': 'Buyurtma raqami',
    'admin.orders.customer': 'Mijoz',
    'admin.orders.date': 'Sana',
    'admin.orders.items': 'Mahsulotlar',
    'admin.orders.payment': 'To‘lov',
    'admin.orders.delivery': 'Yetkazib berish',
    'admin.orders.total': 'Jami summa',
    'admin.orders.status': 'Holati',
    'admin.orders.details': 'Batafsil',
    'admin.orders.allStatuses': 'Barcha holatlar',
    'admin.orders.searchPlaceholder': 'Buyurtma raqami, mijoz yoki pochta bo‘yicha qidirish...',

    // Order Statuses
    'admin.status.Pending': 'Kutilmoqda',
    'admin.status.Confirmed': 'Tasdiqlangan',
    'admin.status.Processing': 'Jarayonda',
    'admin.status.Shipped': 'Yuborilgan',
    'admin.status.Delivered': 'Yetkazilgan',
    'admin.status.Cancelled': 'Bekor qilingan',
    'admin.status.active': 'Faol',
    'admin.status.inactive': 'Nofaol',
    'admin.status.expired': 'Muddati tugagan',
    'admin.status.approved': 'Tasdiqlangan',
    'admin.status.hidden': 'Yashirilgan',
    'admin.status.pending': 'Kutilmoqda',

    // Customers
    'admin.customers.title': 'Mijozlar',
    'admin.customers.subtitle': 'Ro‘yxatdan o‘tgan mijozlar, buyurtmalar soni va xaridlar tarixi',
    'admin.customers.name': 'Ism',
    'admin.customers.email': 'Elektron pochta',
    'admin.customers.phone': 'Telefon',
    'admin.customers.orders': 'Buyurtmalar',
    'admin.customers.totalSpent': 'Jami sarflangan',
    'admin.customers.registeredDate': 'Ro‘yxatdan o‘tgan sana',
    'admin.customers.status': 'Holati',
    'admin.customers.searchPlaceholder': 'Mijoz ismi yoki elektron pochtasi bo‘yicha qidirish...',

    // Users
    'admin.users.title': 'Foydalanuvchilar',
    'admin.users.subtitle': 'Tizim foydalanuvchilari, rollar va ruxsatlarni boshqarish',
    'admin.users.name': 'Ism',
    'admin.users.email': 'Elektron pochta',
    'admin.users.role': 'Rol',
    'admin.users.status': 'Holati',
    'admin.users.createdDate': 'Yaratilgan sana',
    'admin.users.roleCustomer': 'Mijoz',
    'admin.users.roleAdmin': 'Administrator',
    'admin.users.makeAdmin': 'Admin qilish',
    'admin.users.revokeAdmin': 'Mijoz qilish',
    'admin.users.activate': 'Faollashtirish',
    'admin.users.suspend': 'To‘xtatish',

    // Inventory
    'admin.inventory.title': 'Ombor',
    'admin.inventory.subtitle': 'Mahsulotlar zaxirasi, band qilingan miqdor va ombor chegaralarini nazorat qilish',
    'admin.inventory.product': 'Mahsulot',
    'admin.inventory.sku': 'SKU',
    'admin.inventory.currentStock': 'Joriy zaxira',
    'admin.inventory.reserved': 'Band qilingan',
    'admin.inventory.available': 'Mavjud',
    'admin.inventory.threshold': 'Chegara',
    'admin.inventory.status': 'Holati',
    'admin.inventory.inStock': 'Mavjud',
    'admin.inventory.lowStock': 'Kam qolgan',
    'admin.inventory.outOfStock': 'Tugagan',

    // Deals
    'admin.deals.title': 'Chegirmalar',
    'admin.deals.subtitle': 'Maxsus chegirma aksiyalarini yaratish va muddatlarini belgilash',
    'admin.deals.add': 'Chegirma qo‘shish',
    'admin.deals.product': 'Mahsulot',
    'admin.deals.discountPercent': 'Chegirma foizi',
    'admin.deals.startDate': 'Boshlanish sanasi',
    'admin.deals.endDate': 'Tugash sanasi',
    'admin.deals.limitAmount': 'Chegara miqdori',
    'admin.deals.active': 'Faol',
    'admin.deals.expired': 'Muddati tugagan',

    // Reviews
    'admin.reviews.title': 'Sharhlar',
    'admin.reviews.subtitle': 'Mijozlar tomonidan qoldirilgan sharhlarni tekshirish va tasdiqlash',
    'admin.reviews.customer': 'Mijoz',
    'admin.reviews.product': 'Mahsulot',
    'admin.reviews.rating': 'Reyting',
    'admin.reviews.review': 'Sharh',
    'admin.reviews.date': 'Sana',
    'admin.reviews.status': 'Holati',
    'admin.reviews.approve': 'Tasdiqlash',
    'admin.reviews.hide': 'Yashirish',
    'admin.reviews.delete': 'O‘chirish',

    // Banners
    'admin.banners.title': 'Bannerlar',
    'admin.banners.subtitle': 'Bosh sahifa reklama bannerlari va aksiyalarini boshqarish',
    'admin.banners.add': 'Banner qo‘shish',
    'admin.banners.headline': 'Sarlavha',
    'admin.banners.subtext': 'Qo‘shimcha matn',
    'admin.banners.image': 'Rasm',
    'admin.banners.buttonText': 'Tugma matni',
    'admin.banners.buttonLink': 'Tugma havolasi',
    'admin.banners.startDate': 'Boshlanish sanasi',
    'admin.banners.endDate': 'Tugash sanasi',
    'admin.banners.status': 'Holati',

    // Analytics
    'admin.analytics.title': 'Tahlil',
    'admin.analytics.subtitle': 'Savdo hajmi, daromad dinamikasi va eng ommabop mahsulotlar tahlili',
    'admin.analytics.revenue': 'Daromad',
    'admin.analytics.orders': 'Buyurtmalar',
    'admin.analytics.customers': 'Mijozlar',
    'admin.analytics.productsSold': 'Sotilgan mahsulotlar',
    'admin.analytics.avgOrderValue': 'O‘rtacha buyurtma qiymati',
    'admin.analytics.topProducts': 'Eng ko‘p sotilgan mahsulotlar',
    'admin.analytics.topBrands': 'Eng mashhur brendlar',
    'admin.analytics.categorySales': 'Kategoriyalar bo‘yicha savdo',
    'admin.analytics.customerGrowth': 'Mijozlar o‘sishi',
    'admin.analytics.noData': 'Ma’lumot mavjud emas',

    // Notifications
    'admin.notifications.title': 'Bildirishnomalar',
    'admin.notifications.subtitle': 'Tizim xabarnomalari, yangi buyurtmalar va ombor ogohlantirishlari',
    'admin.notifications.newOrder': 'Yangi buyurtma',
    'admin.notifications.lowStock': 'Mahsulot kamaydi',
    'admin.notifications.outOfStock': 'Mahsulot tugadi',
    'admin.notifications.newCustomer': 'Yangi mijoz',
    'admin.notifications.newReview': 'Yangi sharh',
    'admin.notifications.markRead': 'O‘qilgan deb belgilash',
    'admin.notifications.markAllRead': 'Barchasini o‘qilgan deb belgilash',

    // Settings
    'admin.settings.title': 'Sozlamalar',
    'admin.settings.subtitle': 'Do‘kon ma’lumotlari, yetkazib berish va xavfsizlik sozlamalari',
    'admin.settings.storeSettings': 'Do‘kon sozlamalari',
    'admin.settings.adminProfile': 'Admin profili',
    'admin.settings.security': 'Xavfsizlik',
    'admin.settings.notifications': 'Bildirishnomalar',
    'admin.settings.deliverySettings': 'Yetkazib berish sozlamalari',
    'admin.settings.orderSettings': 'Buyurtma sozlamalari',
    'admin.settings.storeName': 'Do‘kon nomi',
    'admin.settings.phone': 'Telefon',
    'admin.settings.email': 'Elektron pochta',
    'admin.settings.address': 'Manzil',
    'admin.settings.logo': 'Logotip',
    'admin.settings.socialLinks': 'Ijtimoiy tarmoqlar',
    'admin.settings.standardDeliveryPrice': 'Oddiy yetkazib berish narxi',
    'admin.settings.expressDeliveryPrice': 'Tezkor yetkazib berish narxi',
    'admin.settings.freeDeliveryThreshold': 'Bepul yetkazib berish chegarasi',

    // Empty / Error / Loading states
    'admin.state.loading': 'Ma’lumot yuklanmoqda...',
    'admin.state.noProducts': 'Mahsulotlar topilmadi.',
    'admin.state.noOrders': 'Buyurtmalar topilmadi.',
    'admin.state.noCustomers': 'Mijozlar topilmadi.',
    'admin.state.noReviews': 'Sharhlar topilmadi.',
    'admin.state.noData': 'Hozircha ma’lumot mavjud emas.',
    'admin.state.error': 'Xatolik yuz berdi.',
    'admin.state.loadFailed': 'Ma’lumotni yuklab bo‘lmadi.',
    'admin.state.serverError': 'Server bilan bog‘lanishda xatolik.',
    'admin.state.tryAgain': 'Iltimos, qayta urinib ko‘ring.',
  },

  RU: {
    // Navigation & Header
    'nav.home': 'Главная',
    'nav.phones': 'Смартфоны',
    'nav.brands': 'Бренды',
    'nav.compare': 'Сравнение',
    'nav.deals': 'Акции',
    'nav.about': 'О нас',
    'nav.wishlist': 'Избранное',
    'nav.cart': 'Корзина',
    'nav.orders': 'Мои заказы',
    'nav.profile': 'Профиль и настройки',
    'nav.signin': 'Войти',
    'nav.signup': 'Регистрация',
    'nav.signout': 'Выйти',
    'nav.adminPanel': 'Админ Панель',
    'nav.adminControl': 'Панель Управления',
    'nav.searchPlaceholder': 'Поиск смартфона, бренда или характеристик...',
    'nav.searchShort': 'Поиск смартфонов...',
    'nav.welcome': 'Добро пожаловать в NOVA',
    'nav.welcomeSub': 'Войдите, чтобы отслеживать заказы и сохранять устройства.',
    'nav.signedInAs': 'Вы вошли как',
    'nav.storeAdmin': 'Администратор',
    'nav.vipCustomer': 'VIP Клиент',
    'nav.flagshipStudio': 'Флагманская Студия',

    // Hero Section
    'hero.badge': 'Флагманы нового поколения • Официальная гарантия',
    'hero.title1': 'БУДУЩЕЕ',
    'hero.title2': 'В ВАШИХ РУКАХ.',
    'hero.subtitle': 'Откройте для себя самые мощные флагманские смартфоны — производительность ИИ, профессиональные камеры и технологии будущего.',
    'hero.exploreBtn': 'Смотреть смартфоны',
    'hero.dealsBtn': 'Смотреть акции',
    'hero.stat1Label': 'Оригинальные устройства',
    'hero.stat2Label': 'Быстрая доставка',
    'hero.stat3Label': 'Официальная гарантия',
    'hero.stat3Val': '1 Год',
    'hero.chipAi': 'МОЩЬ ИИ',
    'hero.chipAiSub': 'Нейронный процессор',
    'hero.chipCamera': 'ПРО КАМЕРА',
    'hero.chipCameraSub': '200МП Оптический зум',
    'hero.chipDisplay': '120Гц ЭКРАН',
    'hero.chipDisplaySub': 'LTPO OLED Матрица',
    'hero.chipBattery': 'ЗАРЯД НА ВЕСЬ ДЕНЬ',
    'hero.chipBatterySub': '100Вт Супер Зарядка',
    'hero.StartingAt': 'Цена от',
    'hero.viewDevice': 'Подробнее',

    // Trust Section
    'trust.warrantyTitle': 'Официальная гарантия 1 год',
    'trust.warrantyDesc': 'Все смартфоны на 100% оригинальные и обеспечены официальным сервисным обслуживанием.',
    'trust.deliveryTitle': 'Экспресс Доставка',
    'trust.deliveryDesc': 'Быстрая и застрахованная курьерская доставка до вашей двери.',
    'trust.originalTitle': '100% Оригинальная Продукция',
    'trust.originalDesc': 'Прямые поставки от официальных производителей в запечатанной упаковке.',
    'trust.installmentTitle': 'Рассрочка 0%',
    'trust.installmentDesc': 'Удобная оплата частями до 12 месяцев без переплат и скрытых комиссий.',
    'trust.supportTitle': 'Поддержка экспертов 24/7',
    'trust.supportDesc': 'Наши технические специалисты готовы помочь с выбором и настройкой.',

    // Home Sections
    'home.brandsBadge': 'Официальные Партнеры',
    'home.brandsTitle': 'Выбор по бренду',
    'home.brandsSub': 'Оригинальные смартфоны от ведущих мировых технологических гигантов',
    'home.viewAllBrands': 'Все бренды',
    'home.modelsCount': 'моделей',
    'home.featuredBadge': 'Флагманская Коллекция',
    'home.featuredTitle': 'Рекомендуемые Смартфоны',
    'home.viewAll': 'Смотреть все',
    'home.flashBadge': 'Ограниченное предложение',
    'home.flashTitle': 'Горячие Скидки и Акции',
    'home.flashSub': 'Успейте приобрести топовые флагманы по специальным сниженным ценам.',
    'home.hours': 'ЧАС',
    'home.mins': 'МИН',
    'home.secs': 'СЕК',
    'home.bestSellersBadge': 'Выбор покупателей',
    'home.bestSellersTitle': 'Хиты Продаж',
    'home.newArrivalsBadge': 'Новые Релизы',
    'home.newArrivalsTitle': 'Новинки Каталога',
    'home.recentBadge': 'История просмотров',
    'home.recentTitle': 'Недавно просмотренные и рекомендации',
    'home.newsletterBadge': 'Вступайте в VIP Клуб',
    'home.newsletterTitle': 'Узнавайте первыми о закрытых распродажах и новых флагманах',
    'home.newsletterSub': 'Оставьте ваш email и получите эксклюзивный промокод на первую покупку.',
    'home.newsletterPlaceholder': 'Введите ваш email адрес...',
    'home.newsletterBtn': 'Подписаться',
    'home.newsletterSuccess': 'Поздравляем! Вы успешно подписались на VIP-рассылку NOVA.',

    // Product Card & Common Actions
    'product.inStock': 'В наличии',
    'product.lowStock': 'Мало на складе',
    'product.outOfStock': 'Нет в наличии',
    'product.left': 'шт. осталось',
    'product.addToCart': 'В корзину',
    'product.addedToCart': 'Добавлено в корзину',
    'product.buyNow': 'Купить сейчас',
    'product.viewDetails': 'Подробнее',
    'product.compare': 'Сравнить',
    'product.wishlist': 'В избранное',
    'product.reviews': 'отзывов',
    'product.save': 'Выгода',
    'product.hotDeal': 'СКИДКА',
    'product.new': 'НОВИНКА',
    'product.bestSeller': 'ХИТ',
    'product.retry': 'Повторить попытку',
    'product.errorLoading': 'Произошла ошибка при загрузке данных.',

    // Catalog / Phones Page
    'catalog.badge': 'Каталог NOVA',
    'catalog.title': 'Найдите свой идеальный смартфон',
    'catalog.subtitle': 'Используйте умные фильтры для подбора идеального флагманского устройства',
    'catalog.filters': 'Фильтры',
    'catalog.clearAll': 'Сбросить',
    'catalog.showing': 'Показано',
    'catalog.devices': 'смартфонов',
    'catalog.sortBy': 'Сортировка:',
    'catalog.sortPopular': 'По популярности',
    'catalog.sortNewest': 'Сначала новинки',
    'catalog.sortPriceAsc': 'Цена: по возрастанию',
    'catalog.sortPriceDesc': 'Цена: по убыванию',
    'catalog.sortRating': 'По высокому рейтингу',
    'catalog.brand': 'Бренд',
    'catalog.priceRange': 'Диапазон цен',
    'catalog.ram': 'Оперативная память (RAM)',
    'catalog.storage': 'Встроенная память',
    'catalog.camera': 'Основная камера',
    'catalog.battery': 'Емкость батареи',
    'catalog.display': 'Тип дисплея',
    'catalog.refreshRate': 'Частота обновления',
    'catalog.os': 'Операционная система',
    'catalog.rating': 'Минимальный рейтинг',
    'catalog.availability': 'Наличие',
    'catalog.inStockOnly': 'Только в наличии',
    'catalog.noResults': 'Смартфоны не найдены',
    'catalog.noResultsSub': 'Попробуйте изменить параметры поиска или сбросить фильтры.',
    'catalog.resetFilters': 'Сбросить фильтры',
    'catalog.all': 'Все',

    // Product Detail Page
    'detail.backToCatalog': 'Назад в каталог',
    'detail.color': 'Выберите цвет',
    'detail.storage': 'Объем памяти',
    'detail.ram': 'Оперативная память (RAM)',
    'detail.installment': 'Рассрочка 0%:',
    'detail.perMonth': '/ в месяц (12 мес.)',
    'detail.deliveryInfo': 'Бесплатная доставка за 2 часа по городу и за 24 часа по регионам',
    'detail.warrantyInfo': 'Официальная гарантия 1 год + 14 дней на обмен и возврат',
    'detail.tabOverview': 'Обзор',
    'detail.tabSpecs': 'Характеристики',
    'detail.tabCamera': 'Камера и Видео',
    'detail.tabBattery': 'Батарея и Дисплей',
    'detail.tabReviews': 'Отзывы покупателей',
    'detail.specDisplay': 'Дисплей',
    'detail.specProcessor': 'Процессор',
    'detail.specRam': 'Оперативная память',
    'detail.specStorage': 'Встроенная память',
    'detail.specMainCam': 'Основная камера',
    'detail.specFrontCam': 'Фронтальная камера',
    'detail.specBattery': 'Аккумулятор',
    'detail.specCharging': 'Зарядка',
    'detail.specRefresh': 'Частота экрана',
    'detail.specOs': 'Операционная система',
    'detail.specWeight': 'Вес',
    'detail.specDimensions': 'Размеры',
    'detail.writeReview': 'Оставить отзыв',
    'detail.yourRating': 'Ваша оценка',
    'detail.reviewTitle': 'Заголовок',
    'detail.reviewComment': 'Ваш комментарий',
    'detail.reviewPros': 'Достоинства',
    'detail.reviewCons': 'Недостатки',
    'detail.submitReview': 'Отправить отзыв',
    'detail.relatedTitle': 'Похожие Флагманы',
    'detail.notFound': 'Смартфон не найден',

    // Brands Page
    'brands.title': 'Официальные Бренды и Партнеры',
    'brands.subtitle': 'NOVA MOBILE является авторизованным партнером ведущих мировых производителей. Каждое устройство оригинально и сертифицировано.',
    'brands.exploreModels': 'Смотреть модели',

    // Deals Page
    'deals.badge': 'Специальные предложения',
    'deals.title': 'Горячие Скидки и Распродажа Флагманов',
    'deals.subtitle': 'Приобретайте новейшие смартфоны по сниженным ценам. Количество товара по акции ограничено.',

    // Compare Page
    'compare.title': 'Сравнение Смартфонов',
    'compare.subtitle': 'Сравните до 3 смартфонов по детальным техническим характеристикам',
    'compare.emptyTitle': 'Список сравнения пуст',
    'compare.emptySub': 'Добавьте минимум 2 смартфона из каталога для наглядного сравнения характеристик.',
    'compare.browsePhones': 'Перейти в каталог',
    'compare.clearAll': 'Очистить список',
    'compare.addDevice': 'Добавить смартфон',
    'compare.parameter': 'Параметр',
    'compare.price': 'Цена',
    'compare.rating': 'Рейтинг',

    // Wishlist Page
    'wishlist.title': 'Избранные Смартфоны',
    'wishlist.subtitle': 'Список сохраненных вами флагманских устройств',
    'wishlist.emptyTitle': 'Список избранного пуст',
    'wishlist.emptySub': 'Нажимайте на иконку сердечка на карточке товара, чтобы сохранить смартфоны на потом.',
    'wishlist.moveAllToCart': 'Добавить все в корзину',

    // Cart & Quick Cart Drawer
    'cart.title': 'Корзина Покупок',
    'cart.emptyTitle': 'Ваша корзина пока пуста',
    'cart.emptySub': 'Выберите свой идеальный флагман в нашем каталоге и добавьте его в корзину.',
    'cart.continueShopping': 'Продолжить покупки',
    'cart.orderSummary': 'Сумма заказа',
    'cart.subtotal': 'Стоимость товаров',
    'cart.discount': 'Скидка',
    'cart.shipping': 'Доставка',
    'cart.free': 'Бесплатно',
    'cart.tax': 'Налоги и сборы (0%)',
    'cart.total': 'Итого к оплате',
    'cart.promoPlaceholder': 'Введите промокод (напр. NOVA10)',
    'cart.apply': 'Применить',
    'cart.checkoutBtn': 'Перейти к оформлению',
    'cart.viewCart': 'Открыть корзину',
    'cart.clearCart': 'Очистить корзину',

    // Checkout Page
    'checkout.title': 'Оформление Заказа',
    'checkout.subtitle': 'Заполните контактные данные и выберите удобный способ оплаты',
    'checkout.step1': '1. Контактные данные',
    'checkout.step2': '2. Адрес и способ доставки',
    'checkout.step3': '3. Способ оплаты',
    'checkout.fullName': 'ФИО полностью',
    'checkout.phone': 'Номер телефона',
    'checkout.email': 'Электронная почта',
    'checkout.deliveryMethod': 'Способ доставки',
    'checkout.standardDelivery': 'Стандартная доставка курьером (Бесплатно • 24 часа)',
    'checkout.expressDelivery': 'VIP Экспресс доставка (За 2 часа • $15)',
    'checkout.storePickup': 'Самовывоз из фирменного шоурума (Бесплатно)',
    'checkout.region': 'Область / Регион',
    'checkout.city': 'Город / Район',
    'checkout.address': 'Улица, дом, квартира',
    'checkout.notes': 'Комментарий курьеру (необязательно)',
    'checkout.payCard': 'Банковская карта онлайн (Uzcard / Humo / Visa / MasterCard)',
    'checkout.payPayme': 'Payme / Click / Uzum Pay',
    'checkout.payCash': 'Наличными или картой при получении',
    'checkout.payInstallment': 'Рассрочка (12 месяцев • 0% первоначальный взнос)',
    'checkout.placeOrder': 'Подтвердить заказ',
    'checkout.processing': 'Оформление...',

    // Order Success & Orders Page
    'success.badge': 'Заказ Оформлен',
    'success.title': 'ВАШ ЗАКАЗ ПРИНЯТ',
    'success.subtitle': 'Спасибо за покупку! Наш менеджер свяжется с вами в ближайшее время для подтверждения доставки.',
    'success.orderId': 'Номер заказа',
    'success.status': 'Статус',
    'success.payment': 'Способ оплаты',
    'success.totalPaid': 'Итоговая сумма',
    'success.viewOrders': 'Мои заказы',
    'success.backHome': 'На главную страницу',
    'orders.title': 'История Заказов',
    'orders.subtitle': 'Отслеживайте статус доставки и историю ваших покупок в NOVA MOBILE',
    'orders.emptyTitle': 'У вас пока нет заказов',
    'orders.emptySub': 'Оформите заказ на свой первый флагманский смартфон уже сегодня.',

    // Profile & Auth Pages
    'auth.signInTitle': 'Вход в аккаунт',
    'auth.signUpTitle': 'Регистрация аккаунта',
    'auth.subtitle': 'Управляйте заказами, избранными смартфонами и персональными привилегиями.',
    'auth.signInTab': 'Войти',
    'auth.signUpTab': 'Регистрация',
    'auth.adminPanelTab': 'Админ Панель',
    'auth.adminLoginLink': 'Вход для администратора',
    'auth.fullName': 'Полное имя',
    'auth.email': 'Email адрес',
    'auth.phone': 'Номер телефона',
    'auth.password': 'Пароль',
    'auth.confirmPassword': 'Подтвердите пароль',
    'auth.showPassword': 'Показать пароль',
    'auth.hidePassword': 'Скрыть пароль',
    'auth.signInBtn': 'Войти',
    'auth.signUpBtn': 'Регистрация',
    'auth.passwordMismatch': 'Пароли не совпадают!',
    'auth.passwordTooShort': 'Пароль должен содержать минимум 6 символов!',
    'auth.fillRequired': 'Пожалуйста, заполните все обязательные поля!',
    'auth.welcomeBack': 'С возвращением в NOVA MOBILE!',
    'auth.accountCreated': 'Аккаунт успешно создан!',
    'auth.demoProfiles': 'Быстрый вход (Демо)',
    'auth.customerDemo': 'Профиль Клиента',
    'auth.savedDelivery': 'Данные доставки',
    'auth.savedWishlist': 'Избранные товары',
    'auth.editProfileTitle': 'Редактировать личные данные и адрес доставки',
    'auth.saveChanges': 'Сохранить изменения',
    'auth.profileUpdated': 'Профиль успешно обновлен!',

    // About Page
    'about.badge': 'О компании NOVA MOBILE',
    'about.title': 'Премиальная студия флагманских смартфонов №1',
    'about.subtitle': 'Мы предлагаем исключительно 100% оригинальные смартфоны с официальной гарантией и первоклассным сервисом.',
    'about.missionTitle': 'Наша Миссия',
    'about.missionDesc': 'Обеспечить каждому клиенту безупречный опыт покупки, честные цены и надежную официальную гарантию.',

    // Footer
    'footer.desc': 'Официальный онлайн-бутик флагманских смартфонов и технологий будущего. Гарантия 1 год и быстрая доставка.',
    'footer.shop': 'Каталог',
    'footer.company': 'Компания',
    'footer.support': 'Поддержка клиентов',
    'footer.contact': 'Контакты',
    'footer.rights': 'Все права защищены.',
    'footer.address': 'г. Ташкент, Tashkent City, Boulevard, дом 14',
    'footer.hours': 'Режим работы: Ежедневно 09:00 — 22:00',

    // ==================================================
    // ADMIN PANEL TRANSLATIONS (RU)
    // ==================================================
    'admin.sidebar.control': 'Управление',
    'admin.sidebar.dashboard': 'Главная',
    'admin.sidebar.products': 'Товары',
    'admin.sidebar.orders': 'Заказы',
    'admin.sidebar.customers': 'Клиенты',
    'admin.sidebar.users': 'Пользователи',
    'admin.sidebar.brands': 'Бренды',
    'admin.sidebar.categories': 'Категории',
    'admin.sidebar.inventory': 'Склад',
    'admin.sidebar.deals': 'Скидки',
    'admin.sidebar.reviews': 'Отзывы',
    'admin.sidebar.banners': 'Баннеры',
    'admin.sidebar.analytics': 'Аналитика',
    'admin.sidebar.notifications': 'Уведомления',
    'admin.sidebar.settings': 'Настройки',
    'admin.sidebar.profile': 'Профиль админа',
    'admin.sidebar.logout': 'Выйти',
    'admin.sidebar.liveStore': 'Перейти в магазин',

    // Admin Login
    'admin.login.title': 'Вход для администратора',
    'admin.login.subtitle': 'Авторизованный доступ в панель управления NOVA MOBILE',
    'admin.login.email': 'Электронная почта',
    'admin.login.password': 'Пароль',
    'admin.login.forgotPassword': 'Забыли пароль?',
    'admin.login.rememberMe': 'Запомнить меня',
    'admin.login.encryptedSession': 'Защищенная JWT сессия',
    'admin.login.submit': 'Войти',
    'admin.login.verifying': 'Проверка...',
    'admin.login.returnStore': 'Вернуться в магазин',
    'admin.login.resetTitle': 'Сброс пароля администратора',
    'admin.login.resetDesc': 'Введите email администратора или обновите переменную ADMIN_PASSWORD на сервере.',
    'admin.login.sendRecovery': 'Отправить инструкцию',
    'admin.login.recoverySent': 'Инструкция отправлена на почту администратора.',
    'admin.login.accessDenied': 'Доступ запрещен: требуются права администратора.',

    // Dashboard
    'admin.dashboard.title': 'Главная панель',
    'admin.dashboard.subtitle': 'Обзор ключевых показателей магазина, заказов и складских запасов',
    'admin.dashboard.totalRevenue': 'Общий доход',
    'admin.dashboard.totalOrders': 'Всего заказов',
    'admin.dashboard.totalProducts': 'Всего товаров',
    'admin.dashboard.totalCustomers': 'Всего клиентов',
    'admin.dashboard.pendingOrders': 'Ожидающие заказы',
    'admin.dashboard.completedOrders': 'Выполненные заказы',
    'admin.dashboard.lowStock': 'Мало на складе',
    'admin.dashboard.avgOrderValue': 'Средний чек',
    'admin.dashboard.revenueGrowth': '+14.8% к прошлому периоду',
    'admin.dashboard.fulfillmentRate': '98.6% выполненных заказов',
    'admin.dashboard.acrossBrands': 'Официальные бренды',
    'admin.dashboard.activeProfiles': 'Активные профили клиентов',
    'admin.dashboard.recentOrders': 'Последние заказы',
    'admin.dashboard.allOrders': 'Все заказы',
    'admin.dashboard.restock': 'Пополнить',
    'admin.dashboard.allStocked': 'Все товары в достаточном количестве.',
    'admin.dashboard.unitsRemaining': 'шт. осталось',

    // Charts & Date filters
    'admin.chart.revenue': 'Доход',
    'admin.chart.orders': 'Заказы',
    'admin.chart.productsSold': 'Продано товаров',
    'admin.chart.customerGrowth': 'Рост клиентов',
    'admin.date.today': 'Сегодня',
    'admin.date.7d': '7 дней',
    'admin.date.30d': '30 дней',
    'admin.date.3m': '3 мес.',
    'admin.date.12m': '12 мес.',

    // Common Buttons & Actions
    'admin.btn.save': 'Сохранить',
    'admin.btn.cancel': 'Отмена',
    'admin.btn.update': 'Обновить',
    'admin.btn.confirm': 'Подтвердить',
    'admin.btn.delete': 'Удалить',
    'admin.btn.edit': 'Редактировать',
    'admin.btn.view': 'Просмотр',
    'admin.btn.duplicate': 'Копировать',
    'admin.btn.search': 'Поиск',
    'admin.btn.filter': 'Фильтр',
    'admin.btn.sort': 'Сортировка',
    'admin.btn.close': 'Закрыть',
    'admin.btn.actions': 'Действия',

    // Products
    'admin.products.title': 'Товары',
    'admin.products.subtitle': 'Управление каталогом смартфонов, характеристиками и ценами',
    'admin.products.addNew': 'Добавить товар',
    'admin.products.editProduct': 'Редактировать',
    'admin.products.deleteConfirmTitle': 'Удалить этот товар?',
    'admin.products.deleteConfirmDesc': 'Товар будет полностью удален из базы данных и витрины магазина:',
    'admin.products.searchPlaceholder': 'Поиск по названию, бренду или SKU...',
    'admin.products.name': 'Название товара',
    'admin.products.brand': 'Бренд',
    'admin.products.category': 'Категория',
    'admin.products.description': 'Описание',
    'admin.products.price': 'Цена',
    'admin.products.oldPrice': 'Старая цена',
    'admin.products.discount': 'Скидка',
    'admin.products.stock': 'Количество на складе',
    'admin.products.sku': 'SKU',
    'admin.products.ram': 'Оперативная память',
    'admin.products.storage': 'Встроенная память',
    'admin.products.processor': 'Процессор',
    'admin.products.display': 'Дисплей',
    'admin.products.camera': 'Камера',
    'admin.products.battery': 'Батарея',
    'admin.products.os': 'Операционная система',
    'admin.products.colors': 'Цвета',
    'admin.products.images': 'Изображения',
    'admin.products.uploadImage': 'Загрузить фото',
    'admin.products.imagePlaceholder': 'Вставьте ссылку (URL) или загрузите файл...',
    'admin.products.selectBrand': 'Выберите бренд...',
    'admin.products.selectCategory': 'Выберите категорию...',
    'admin.products.featured': 'Рекомендуемый товар',
    'admin.products.bestSeller': 'Хит продаж',
    'admin.products.newArrival': 'Новинка',
    'admin.products.deal': 'Товар со скидкой',
    'admin.products.units': 'шт.',
    'admin.products.errName': 'Введите название товара.',
    'admin.products.errBrand': 'Выберите бренд.',
    'admin.products.errCategory': 'Выберите категорию.',
    'admin.products.errPrice': 'Введите цену.',
    'admin.products.errStock': 'Укажите количество на складе.',
    'admin.products.errImage': 'Загрузите изображение.',

    // Categories
    'admin.categories.title': 'Категории',
    'admin.categories.subtitle': 'Управление категориями смартфонов',
    'admin.categories.add': 'Добавить категорию',
    'admin.categories.edit': 'Редактировать категорию',
    'admin.categories.delete': 'Удалить категорию',
    'admin.categories.productCount': 'Количество товаров',
    'admin.categories.name': 'Название категории',

    // Brands
    'admin.brands.title': 'Бренды',
    'admin.brands.subtitle': 'Управление официальными брендами-партнерами',
    'admin.brands.add': 'Добавить бренд',
    'admin.brands.edit': 'Редактировать бренд',
    'admin.brands.delete': 'Удалить бренд',
    'admin.brands.name': 'Название бренда',
    'admin.brands.logo': 'Логотип',
    'admin.brands.description': 'Описание',
    'admin.brands.status': 'Статус',

    // Orders
    'admin.orders.title': 'Заказы',
    'admin.orders.subtitle': 'Управление заказами клиентов, доставкой и статусами',
    'admin.orders.orderNumber': 'Номер заказа',
    'admin.orders.customer': 'Клиент',
    'admin.orders.date': 'Дата',
    'admin.orders.items': 'Товары',
    'admin.orders.payment': 'Оплата',
    'admin.orders.delivery': 'Доставка',
    'admin.orders.total': 'Общая сумма',
    'admin.orders.status': 'Статус',
    'admin.orders.details': 'Подробнее',
    'admin.orders.allStatuses': 'Все статусы',
    'admin.orders.searchPlaceholder': 'Поиск по номеру заказа, клиенту или email...',

    // Order Statuses
    'admin.status.Pending': 'Ожидается',
    'admin.status.Confirmed': 'Подтвержден',
    'admin.status.Processing': 'В обработке',
    'admin.status.Shipped': 'Отправлен',
    'admin.status.Delivered': 'Доставлен',
    'admin.status.Cancelled': 'Отменен',
    'admin.status.active': 'Активен',
    'admin.status.inactive': 'Неактивен',
    'admin.status.expired': 'Истек',
    'admin.status.approved': 'Одобрен',
    'admin.status.hidden': 'Скрыт',
    'admin.status.pending': 'Ожидается',

    // Customers
    'admin.customers.title': 'Клиенты',
    'admin.customers.subtitle': 'База зарегистрированных покупателей и история заказов',
    'admin.customers.name': 'Имя',
    'admin.customers.email': 'Электронная почта',
    'admin.customers.phone': 'Телефон',
    'admin.customers.orders': 'Заказы',
    'admin.customers.totalSpent': 'Всего потрачено',
    'admin.customers.registeredDate': 'Дата регистрации',
    'admin.customers.status': 'Статус',
    'admin.customers.searchPlaceholder': 'Поиск клиентов по имени или email...',

    // Users
    'admin.users.title': 'Пользователи',
    'admin.users.subtitle': 'Управление учетными записями и ролями доступа',
    'admin.users.name': 'Имя',
    'admin.users.email': 'Электронная почта',
    'admin.users.role': 'Роль',
    'admin.users.status': 'Статус',
    'admin.users.createdDate': 'Дата создания',
    'admin.users.roleCustomer': 'Клиент',
    'admin.users.roleAdmin': 'Администратор',
    'admin.users.makeAdmin': 'Сделать админом',
    'admin.users.revokeAdmin': 'Сделать клиентом',
    'admin.users.activate': 'Активировать',
    'admin.users.suspend': 'Заблокировать',

    // Inventory
    'admin.inventory.title': 'Склад',
    'admin.inventory.subtitle': 'Контроль остатков, резервов и пороговых значений',
    'admin.inventory.product': 'Товар',
    'admin.inventory.sku': 'SKU',
    'admin.inventory.currentStock': 'Текущий запас',
    'admin.inventory.reserved': 'В резерве',
    'admin.inventory.available': 'Доступно',
    'admin.inventory.threshold': 'Порог',
    'admin.inventory.status': 'Статус',
    'admin.inventory.inStock': 'В наличии',
    'admin.inventory.lowStock': 'Мало на складе',
    'admin.inventory.outOfStock': 'Нет в наличии',

    // Deals
    'admin.deals.title': 'Скидки',
    'admin.deals.subtitle': 'Управление акциями и специальными предложениями',
    'admin.deals.add': 'Добавить скидку',
    'admin.deals.product': 'Товар',
    'admin.deals.discountPercent': 'Процент скидки',
    'admin.deals.startDate': 'Дата начала',
    'admin.deals.endDate': 'Дата окончания',
    'admin.deals.limitAmount': 'Лимит количества',
    'admin.deals.active': 'Активна',
    'admin.deals.expired': 'Истекла',

    // Reviews
    'admin.reviews.title': 'Отзывы',
    'admin.reviews.subtitle': 'Модерация отзывов покупателей',
    'admin.reviews.customer': 'Клиент',
    'admin.reviews.product': 'Товар',
    'admin.reviews.rating': 'Рейтинг',
    'admin.reviews.review': 'Отзыв',
    'admin.reviews.date': 'Дата',
    'admin.reviews.status': 'Статус',
    'admin.reviews.approve': 'Подтвердить',
    'admin.reviews.hide': 'Скрыть',
    'admin.reviews.delete': 'Удалить',

    // Banners
    'admin.banners.title': 'Баннеры',
    'admin.banners.subtitle': 'Управление рекламными баннерами на главной странице',
    'admin.banners.add': 'Добавить баннер',
    'admin.banners.headline': 'Заголовок',
    'admin.banners.subtext': 'Дополнительный текст',
    'admin.banners.image': 'Изображение',
    'admin.banners.buttonText': 'Текст кнопки',
    'admin.banners.buttonLink': 'Ссылка кнопки',
    'admin.banners.startDate': 'Дата начала',
    'admin.banners.endDate': 'Дата окончания',
    'admin.banners.status': 'Статус',

    // Analytics
    'admin.analytics.title': 'Аналитика',
    'admin.analytics.subtitle': 'Подробная статистика продаж, доходов и популярных товаров',
    'admin.analytics.revenue': 'Доход',
    'admin.analytics.orders': 'Заказы',
    'admin.analytics.customers': 'Клиенты',
    'admin.analytics.productsSold': 'Продано товаров',
    'admin.analytics.avgOrderValue': 'Средний чек',
    'admin.analytics.topProducts': 'Самые продаваемые товары',
    'admin.analytics.topBrands': 'Популярные бренды',
    'admin.analytics.categorySales': 'Продажи по категориям',
    'admin.analytics.customerGrowth': 'Рост клиентов',
    'admin.analytics.noData': 'Нет данных',

    // Notifications
    'admin.notifications.title': 'Уведомления',
    'admin.notifications.subtitle': 'Системные оповещения о новых заказах, клиентах и остатках на складе',
    'admin.notifications.newOrder': 'Новый заказ',
    'admin.notifications.lowStock': 'Мало товара',
    'admin.notifications.outOfStock': 'Товар закончился',
    'admin.notifications.newCustomer': 'Новый клиент',
    'admin.notifications.newReview': 'Новый отзыв',
    'admin.notifications.markRead': 'Отметить прочитанным',
    'admin.notifications.markAllRead': 'Отметить все прочитанными',

    // Settings
    'admin.settings.title': 'Настройки',
    'admin.settings.subtitle': 'Настройки магазина, доставки и безопасности',
    'admin.settings.storeSettings': 'Настройки магазина',
    'admin.settings.adminProfile': 'Профиль админа',
    'admin.settings.security': 'Безопасность',
    'admin.settings.notifications': 'Уведомления',
    'admin.settings.deliverySettings': 'Настройки доставки',
    'admin.settings.orderSettings': 'Настройки заказов',
    'admin.settings.storeName': 'Название магазина',
    'admin.settings.phone': 'Телефон',
    'admin.settings.email': 'Электронная почта',
    'admin.settings.address': 'Адрес',
    'admin.settings.logo': 'Логотип',
    'admin.settings.socialLinks': 'Социальные сети',
    'admin.settings.standardDeliveryPrice': 'Стоимость обычной доставки',
    'admin.settings.expressDeliveryPrice': 'Стоимость экспресс-доставки',
    'admin.settings.freeDeliveryThreshold': 'Порог бесплатной доставки',

    // Empty / Error / Loading states
    'admin.state.loading': 'Загрузка данных...',
    'admin.state.noProducts': 'Товары не найдены.',
    'admin.state.noOrders': 'Заказы не найдены.',
    'admin.state.noCustomers': 'Клиенты не найдены.',
    'admin.state.noReviews': 'Отзывы не найдены.',
    'admin.state.noData': 'Данные пока отсутствуют.',
    'admin.state.error': 'Произошла ошибка.',
    'admin.state.loadFailed': 'Не удалось загрузить данные.',
    'admin.state.serverError': 'Ошибка соединения с сервером.',
    'admin.state.tryAgain': 'Пожалуйста, попробуйте еще раз.',
  },

  EN: {
    // Navigation & Header
    'nav.home': 'Home',
    'nav.phones': 'Phones',
    'nav.brands': 'Brands',
    'nav.compare': 'Compare',
    'nav.deals': 'Deals',
    'nav.about': 'About',
    'nav.wishlist': 'Wishlist',
    'nav.cart': 'Cart',
    'nav.orders': 'Order History',
    'nav.profile': 'My Profile & Settings',
    'nav.signin': 'Sign In',
    'nav.signup': 'Sign Up',
    'nav.signout': 'Sign Out',
    'nav.adminPanel': 'Admin Panel',
    'nav.adminControl': 'Admin Control Panel',
    'nav.searchPlaceholder': 'Search by smartphone, brand, or specification...',
    'nav.searchShort': 'Search phones...',
    'nav.welcome': 'Welcome to NOVA',
    'nav.welcomeSub': 'Sign in to track orders and save flagship devices.',
    'nav.signedInAs': 'Signed in as',
    'nav.storeAdmin': 'Administrator',
    'nav.vipCustomer': 'VIP Customer',
    'nav.flagshipStudio': 'Flagship Studio',

    // Hero Section
    'hero.badge': 'Next-Gen Flagships • Official Warranty',
    'hero.title1': 'THE FUTURE',
    'hero.title2': 'IN YOUR HANDS.',
    'hero.subtitle': 'Discover the most powerful flagship smartphones — AI performance, pro-grade camera systems, and next-generation engineering.',
    'hero.exploreBtn': 'Explore Smartphones',
    'hero.dealsBtn': 'View Deals',
    'hero.stat1Label': 'Authentic Devices',
    'hero.stat2Label': 'Express Delivery',
    'hero.stat3Label': 'Official Warranty',
    'hero.stat3Val': '1 Year',
    'hero.chipAi': 'AI POWER',
    'hero.chipAiSub': 'Neural Engine',
    'hero.chipCamera': 'PRO CAMERA',
    'hero.chipCameraSub': '200MP Periscope Zoom',
    'hero.chipDisplay': '120Hz DISPLAY',
    'hero.chipDisplaySub': 'LTPO OLED Brilliance',
    'hero.chipBattery': 'ALL-DAY BATTERY',
    'hero.chipBatterySub': '100W HyperCharge',
    'hero.StartingAt': 'Starting at',
    'hero.viewDevice': 'View Device',

    // Trust Section
    'trust.warrantyTitle': '1-Year Official Warranty',
    'trust.warrantyDesc': 'Every smartphone is 100% authentic and backed by our comprehensive official service guarantee.',
    'trust.deliveryTitle': 'Fast Insured Delivery',
    'trust.deliveryDesc': 'Express doorstep courier delivery with full transit insurance.',
    'trust.originalTitle': '100% Original Products',
    'trust.originalDesc': 'Factory-sealed flagships sourced directly from authorized global manufacturers.',
    'trust.installmentTitle': '0% Installment Plans',
    'trust.installmentDesc': 'Flexible monthly payments up to 12 months with zero hidden fees.',
    'trust.supportTitle': '24/7 Expert Concierge',
    'trust.supportDesc': 'Dedicated hardware specialists ready to assist you anytime.',

    // Home Sections
    'home.brandsBadge': 'Authorized Partners',
    'home.brandsTitle': 'Shop by Brand',
    'home.brandsSub': 'Explore authentic flagship smartphones from global technology leaders',
    'home.viewAllBrands': 'View All Brands',
    'home.modelsCount': 'models',
    'home.featuredBadge': 'Flagship Lineup',
    'home.featuredTitle': 'Featured Smartphones',
    'home.viewAll': 'View All',
    'home.flashBadge': 'Limited Time Offer',
    'home.flashTitle': 'Flash Deals & Exclusive Promotions',
    'home.flashSub': 'Grab top-tier flagship smartphones at special promotional prices before time runs out.',
    'home.hours': 'HRS',
    'home.mins': 'MIN',
    'home.secs': 'SEC',
    'home.bestSellersBadge': 'Customer Favorites',
    'home.bestSellersTitle': 'Best Sellers',
    'home.newArrivalsBadge': 'Just Released',
    'home.newArrivalsTitle': 'New Arrivals',
    'home.recentBadge': 'Browsing History',
    'home.recentTitle': 'Recently Viewed & Recommended',
    'home.newsletterBadge': 'Join the VIP Club',
    'home.newsletterTitle': 'Get early access to flagship launches and private flash sales',
    'home.newsletterSub': 'Subscribe with your email to receive an instant VIP promo code on your next order.',
    'home.newsletterPlaceholder': 'Enter your email address...',
    'home.newsletterBtn': 'Subscribe',
    'home.newsletterSuccess': 'Welcome aboard! You are now subscribed to NOVA VIP updates.',

    // Product Card & Common Actions
    'product.inStock': 'In Stock',
    'product.lowStock': 'Low Stock',
    'product.outOfStock': 'Out of Stock',
    'product.left': 'left in stock',
    'product.addToCart': 'Add to Cart',
    'product.addedToCart': 'Added to Cart',
    'product.buyNow': 'Buy Now',
    'product.viewDetails': 'View Details',
    'product.compare': 'Compare',
    'product.wishlist': 'Wishlist',
    'product.reviews': 'reviews',
    'product.save': 'Save',
    'product.hotDeal': 'HOT DEAL',
    'product.new': 'NEW',
    'product.bestSeller': 'BEST SELLER',
    'product.retry': 'Retry',
    'product.errorLoading': 'Failed to load data. Please try again.',

    // Catalog / Phones Page
    'catalog.badge': 'NOVA Catalog',
    'catalog.title': 'Find Your Perfect Smartphone',
    'catalog.subtitle': 'Use precision filters to discover the flagship engineered for your lifestyle',
    'catalog.filters': 'Filters',
    'catalog.clearAll': 'Clear All',
    'catalog.showing': 'Showing',
    'catalog.devices': 'smartphones',
    'catalog.sortBy': 'Sort by:',
    'catalog.sortPopular': 'Most Popular',
    'catalog.sortNewest': 'Newest Arrivals',
    'catalog.sortPriceAsc': 'Price: Low to High',
    'catalog.sortPriceDesc': 'Price: High to Low',
    'catalog.sortRating': 'Highest Rated',
    'catalog.brand': 'Brand',
    'catalog.priceRange': 'Price Range',
    'catalog.ram': 'RAM Capacity',
    'catalog.storage': 'Storage Capacity',
    'catalog.camera': 'Main Camera',
    'catalog.battery': 'Battery Capacity',
    'catalog.display': 'Display Technology',
    'catalog.refreshRate': 'Refresh Rate',
    'catalog.os': 'Operating System',
    'catalog.rating': 'Minimum Rating',
    'catalog.availability': 'Availability',
    'catalog.inStockOnly': 'In Stock Only',
    'catalog.noResults': 'No matching smartphones found',
    'catalog.noResultsSub': 'Try adjusting your search query or clearing some active filters.',
    'catalog.resetFilters': 'Reset All Filters',
    'catalog.all': 'All',

    // Product Detail Page
    'detail.backToCatalog': 'Back to Catalog',
    'detail.color': 'Select Finish',
    'detail.storage': 'Storage Capacity',
    'detail.ram': 'Memory (RAM)',
    'detail.installment': '0% Installment:',
    'detail.perMonth': '/ mo for 12 mos',
    'detail.deliveryInfo': 'Free 2-hour express city delivery & 24-hour nationwide courier shipping',
    'detail.warrantyInfo': '1-Year Official Warranty + 14-Day Hassle-Free Return Policy',
    'detail.tabOverview': 'Overview',
    'detail.tabSpecs': 'Specifications',
    'detail.tabCamera': 'Camera System',
    'detail.tabBattery': 'Battery & Display',
    'detail.tabReviews': 'Customer Reviews',
    'detail.specDisplay': 'Display',
    'detail.specProcessor': 'Processor',
    'detail.specRam': 'RAM',
    'detail.specStorage': 'Storage',
    'detail.specMainCam': 'Main Camera',
    'detail.specFrontCam': 'Front Camera',
    'detail.specBattery': 'Battery',
    'detail.specCharging': 'Charging',
    'detail.specRefresh': 'Refresh Rate',
    'detail.specOs': 'Operating System',
    'detail.specWeight': 'Weight',
    'detail.specDimensions': 'Dimensions',
    'detail.writeReview': 'Write a Review',
    'detail.yourRating': 'Your Rating',
    'detail.reviewTitle': 'Review Title',
    'detail.reviewComment': 'Your Review',
    'detail.reviewPros': 'Pros',
    'detail.reviewCons': 'Cons',
    'detail.submitReview': 'Submit Review',
    'detail.relatedTitle': 'Related Flagships',
    'detail.notFound': 'Smartphone not found',

    // Brands Page
    'brands.title': 'Official Brands & Partners',
    'brands.subtitle': 'NOVA MOBILE is an authorized flagship partner of the world’s leading technology brands. Every device is 100% genuine.',
    'brands.exploreModels': 'Explore Models',

    // Deals Page
    'deals.badge': 'Limited Time Promotions',
    'deals.title': 'Flash Deals & Flagship Offers',
    'deals.subtitle': 'Experience next-gen smartphones at exclusive promotional prices while supplies last.',

    // Compare Page
    'compare.title': 'Compare Smartphones',
    'compare.subtitle': 'Compare up to 3 flagship smartphones side-by-side across full technical specifications',
    'compare.emptyTitle': 'No devices selected for comparison',
    'compare.emptySub': 'Add at least 2 smartphones from the catalog to compare their specs side-by-side.',
    'compare.browsePhones': 'Browse Smartphones',
    'compare.clearAll': 'Clear Comparison',
    'compare.addDevice': 'Add Smartphone',
    'compare.parameter': 'Specification',
    'compare.price': 'Price',
    'compare.rating': 'Rating',

    // Wishlist Page
    'wishlist.title': 'Saved Wishlist',
    'wishlist.subtitle': 'Your curated collection of favorite flagship smartphones',
    'wishlist.emptyTitle': 'Your wishlist is empty',
    'wishlist.emptySub': 'Tap the heart icon on any smartphone to save it here for later.',
    'wishlist.moveAllToCart': 'Add All to Cart',

    // Cart & Quick Cart Drawer
    'cart.title': 'Shopping Cart',
    'cart.emptyTitle': 'Your cart is currently empty',
    'cart.emptySub': 'Explore our flagship catalog and add your favorite smartphones to the cart.',
    'cart.continueShopping': 'Continue Shopping',
    'cart.orderSummary': 'Order Summary',
    'cart.subtotal': 'Subtotal',
    'cart.discount': 'Discount',
    'cart.shipping': 'Shipping',
    'cart.free': 'Free',
    'cart.tax': 'Estimated Tax (0%)',
    'cart.total': 'Total',
    'cart.promoPlaceholder': 'Enter promo code (e.g. NOVA10)',
    'cart.apply': 'Apply',
    'cart.checkoutBtn': 'Proceed to Checkout',
    'cart.viewCart': 'View Full Cart',
    'cart.clearCart': 'Clear Cart',

    // Checkout Page
    'checkout.title': 'Secure Checkout',
    'checkout.subtitle': 'Complete your delivery details and choose your preferred payment method',
    'checkout.step1': '1. Customer Information',
    'checkout.step2': '2. Shipping & Delivery',
    'checkout.step3': '3. Payment Method',
    'checkout.fullName': 'Full Name',
    'checkout.phone': 'Phone Number',
    'checkout.email': 'Email Address',
    'checkout.deliveryMethod': 'Delivery Option',
    'checkout.standardDelivery': 'Standard Courier Delivery (Free • Within 24 Hours)',
    'checkout.expressDelivery': 'VIP 2-Hour Express Courier ($15)',
    'checkout.storePickup': 'In-Store Showroom Pickup (Free)',
    'checkout.region': 'Region / State',
    'checkout.city': 'City / District',
    'checkout.address': 'Street Address, Building, Apt',
    'checkout.notes': 'Delivery Notes (Optional)',
    'checkout.payCard': 'Credit / Debit Card (Uzcard / Humo / Visa / MasterCard)',
    'checkout.payPayme': 'Payme / Click / Digital Wallet',
    'checkout.payCash': 'Cash or Card on Delivery',
    'checkout.payInstallment': '0% Monthly Installment Plan (12 Months)',
    'checkout.placeOrder': 'Place Order Now',
    'checkout.processing': 'Processing Order...',

    // Order Success & Orders Page
    'success.badge': 'Order Confirmed',
    'success.title': 'YOUR ORDER HAS BEEN RECEIVED',
    'success.subtitle': 'Thank you for choosing NOVA MOBILE! Our concierge team will contact you shortly to confirm dispatch.',
    'success.orderId': 'Order Number',
    'success.status': 'Order Status',
    'success.payment': 'Payment Method',
    'success.totalPaid': 'Total Amount',
    'success.viewOrders': 'View My Orders',
    'success.backHome': 'Return to Homepage',
    'orders.title': 'My Order History',
    'orders.subtitle': 'Track your flagship purchases and real-time delivery status',
    'orders.emptyTitle': 'No orders placed yet',
    'orders.emptySub': 'Discover your next flagship smartphone and place your first order today.',

    // Profile & Auth Pages
    'auth.signInTitle': 'Sign In to NOVA',
    'auth.signUpTitle': 'Create Customer Account',
    'auth.subtitle': 'Access your order history, saved flagships, and VIP member benefits.',
    'auth.signInTab': 'Sign In',
    'auth.signUpTab': 'Sign Up',
    'auth.adminPanelTab': 'Admin Panel',
    'auth.adminLoginLink': 'Admin Login',
    'auth.fullName': 'Full Name',
    'auth.email': 'Email Address',
    'auth.phone': 'Phone Number',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.showPassword': 'Show Password',
    'auth.hidePassword': 'Hide Password',
    'auth.signInBtn': 'Sign In',
    'auth.signUpBtn': 'Sign Up',
    'auth.passwordMismatch': 'Passwords do not match!',
    'auth.passwordTooShort': 'Password must be at least 6 characters long!',
    'auth.fillRequired': 'Please fill in all required fields!',
    'auth.welcomeBack': 'Welcome back to NOVA MOBILE!',
    'auth.accountCreated': 'Customer account created and signed in!',
    'auth.demoProfiles': 'Instant 1-Click Demo Access',
    'auth.customerDemo': 'Customer Profile',
    'auth.savedDelivery': 'Saved Delivery Info',
    'auth.savedWishlist': 'Saved Wishlist',
    'auth.editProfileTitle': 'Edit Account & Shipping Profile',
    'auth.saveChanges': 'Save Profile Changes',
    'auth.profileUpdated': 'Profile updated successfully!',

    // About Page
    'about.badge': 'About NOVA MOBILE',
    'about.title': 'The Premier Flagship Smartphone Destination',
    'about.subtitle': 'We curate 100% original flagship smartphones backed by official warranties and white-glove concierge service.',
    'about.missionTitle': 'Our Mission',
    'about.missionDesc': 'To deliver an uncompromising flagship buying experience with transparent pricing and certified manufacturer support.',

    // Footer
    'footer.desc': 'Official online flagship store for next-generation smartphones. 1-year warranty and express insured delivery.',
    'footer.shop': 'Shop Catalog',
    'footer.company': 'Company',
    'footer.support': 'Customer Care',
    'footer.contact': 'Contact Us',
    'footer.rights': 'All rights reserved.',
    'footer.address': '14 Boulevard St, Tashkent City, Tashkent',
    'footer.hours': 'Open Daily: 09:00 AM — 10:00 PM',

    // ==================================================
    // ADMIN PANEL TRANSLATIONS (EN)
    // ==================================================
    'admin.sidebar.control': 'Control',
    'admin.sidebar.dashboard': 'Dashboard',
    'admin.sidebar.products': 'Products',
    'admin.sidebar.orders': 'Orders',
    'admin.sidebar.customers': 'Customers',
    'admin.sidebar.users': 'Users',
    'admin.sidebar.brands': 'Brands',
    'admin.sidebar.categories': 'Categories',
    'admin.sidebar.inventory': 'Inventory',
    'admin.sidebar.deals': 'Deals',
    'admin.sidebar.reviews': 'Reviews',
    'admin.sidebar.banners': 'Banners',
    'admin.sidebar.analytics': 'Analytics',
    'admin.sidebar.notifications': 'Notifications',
    'admin.sidebar.settings': 'Settings',
    'admin.sidebar.profile': 'Admin Profile',
    'admin.sidebar.logout': 'Log Out',
    'admin.sidebar.liveStore': 'Visit Storefront',

    // Admin Login
    'admin.login.title': 'Admin Login',
    'admin.login.subtitle': 'Authorized administrative management & operations',
    'admin.login.email': 'Admin Email',
    'admin.login.password': 'Password',
    'admin.login.forgotPassword': 'Forgot Password?',
    'admin.login.rememberMe': 'Remember Me',
    'admin.login.encryptedSession': 'Encrypted JWT Session',
    'admin.login.submit': 'Login',
    'admin.login.verifying': 'Verifying...',
    'admin.login.returnStore': 'Return to Public Storefront',
    'admin.login.resetTitle': 'Reset Admin Password',
    'admin.login.resetDesc': 'Enter your registered administrator email address or update ADMIN_PASSWORD in your server environment.',
    'admin.login.sendRecovery': 'Send Recovery Instructions',
    'admin.login.recoverySent': 'Recovery instructions sent to administrator email.',
    'admin.login.accessDenied': 'Access denied: Administrator privileges required.',

    // Dashboard
    'admin.dashboard.title': 'Dashboard',
    'admin.dashboard.subtitle': 'Store performance overview, orders, and inventory status',
    'admin.dashboard.totalRevenue': 'Total Revenue',
    'admin.dashboard.totalOrders': 'Total Orders',
    'admin.dashboard.totalProducts': 'Total Products',
    'admin.dashboard.totalCustomers': 'Total Customers',
    'admin.dashboard.pendingOrders': 'Pending Orders',
    'admin.dashboard.completedOrders': 'Completed Orders',
    'admin.dashboard.lowStock': 'Low Stock Products',
    'admin.dashboard.avgOrderValue': 'Average Order Value',
    'admin.dashboard.revenueGrowth': '+14.8% vs previous period',
    'admin.dashboard.fulfillmentRate': '98.6% fulfillment rate',
    'admin.dashboard.acrossBrands': 'Across official brands',
    'admin.dashboard.activeProfiles': 'Active verified customers',
    'admin.dashboard.recentOrders': 'Recent Orders',
    'admin.dashboard.allOrders': 'All Orders',
    'admin.dashboard.restock': 'Restock',
    'admin.dashboard.allStocked': 'All smartphones sufficiently stocked.',
    'admin.dashboard.unitsRemaining': 'units remaining',

    // Charts & Date filters
    'admin.chart.revenue': 'Revenue',
    'admin.chart.orders': 'Orders',
    'admin.chart.productsSold': 'Products Sold',
    'admin.chart.customerGrowth': 'Customer Growth',
    'admin.date.today': 'Today',
    'admin.date.7d': '7 Days',
    'admin.date.30d': '30 Days',
    'admin.date.3m': '3 Months',
    'admin.date.12m': '12 Months',

    // Common Buttons & Actions
    'admin.btn.save': 'Save',
    'admin.btn.cancel': 'Cancel',
    'admin.btn.update': 'Update',
    'admin.btn.confirm': 'Confirm',
    'admin.btn.delete': 'Delete',
    'admin.btn.edit': 'Edit',
    'admin.btn.view': 'View',
    'admin.btn.duplicate': 'Duplicate',
    'admin.btn.search': 'Search',
    'admin.btn.filter': 'Filter',
    'admin.btn.sort': 'Sort',
    'admin.btn.close': 'Close',
    'admin.btn.actions': 'Actions',

    // Products
    'admin.products.title': 'Products',
    'admin.products.subtitle': 'Manage smartphone catalog, specifications, and pricing',
    'admin.products.addNew': 'Add New Product',
    'admin.products.editProduct': 'Edit',
    'admin.products.deleteConfirmTitle': 'Are you sure you want to delete this product?',
    'admin.products.deleteConfirmDesc': 'This will permanently remove the product from the database and storefront:',
    'admin.products.searchPlaceholder': 'Search by product name, brand, or SKU...',
    'admin.products.name': 'Product Name',
    'admin.products.brand': 'Brand',
    'admin.products.category': 'Category',
    'admin.products.description': 'Description',
    'admin.products.price': 'Price',
    'admin.products.oldPrice': 'Old Price',
    'admin.products.discount': 'Discount',
    'admin.products.stock': 'Stock Quantity',
    'admin.products.sku': 'SKU',
    'admin.products.ram': 'RAM',
    'admin.products.storage': 'Storage',
    'admin.products.processor': 'Processor',
    'admin.products.display': 'Display',
    'admin.products.camera': 'Camera',
    'admin.products.battery': 'Battery',
    'admin.products.os': 'Operating System',
    'admin.products.colors': 'Colors',
    'admin.products.images': 'Images',
    'admin.products.uploadImage': 'Upload Image',
    'admin.products.imagePlaceholder': 'Enter image URL or upload file...',
    'admin.products.selectBrand': 'Select Brand...',
    'admin.products.selectCategory': 'Select Category...',
    'admin.products.featured': 'Featured Product',
    'admin.products.bestSeller': 'Best Seller',
    'admin.products.newArrival': 'New Arrival',
    'admin.products.deal': 'Deal Product',
    'admin.products.units': 'units',
    'admin.products.errName': 'Please enter product name.',
    'admin.products.errBrand': 'Please select a brand.',
    'admin.products.errCategory': 'Please select a category.',
    'admin.products.errPrice': 'Please enter a valid price.',
    'admin.products.errStock': 'Please enter stock quantity.',
    'admin.products.errImage': 'Please upload at least one image.',

    // Categories
    'admin.categories.title': 'Categories',
    'admin.categories.subtitle': 'Organize smartphones by category',
    'admin.categories.add': 'Add Category',
    'admin.categories.edit': 'Edit Category',
    'admin.categories.delete': 'Delete Category',
    'admin.categories.productCount': 'Product Count',
    'admin.categories.name': 'Category Name',

    // Brands
    'admin.brands.title': 'Brands',
    'admin.brands.subtitle': 'Manage official partner smartphone brands',
    'admin.brands.add': 'Add Brand',
    'admin.brands.edit': 'Edit Brand',
    'admin.brands.delete': 'Delete Brand',
    'admin.brands.name': 'Brand Name',
    'admin.brands.logo': 'Logo',
    'admin.brands.description': 'Description',
    'admin.brands.status': 'Status',

    // Orders
    'admin.orders.title': 'Orders',
    'admin.orders.subtitle': 'Manage customer orders, shipping, and fulfillment statuses',
    'admin.orders.orderNumber': 'Order Number',
    'admin.orders.customer': 'Customer',
    'admin.orders.date': 'Date',
    'admin.orders.items': 'Items',
    'admin.orders.payment': 'Payment',
    'admin.orders.delivery': 'Delivery',
    'admin.orders.total': 'Total Amount',
    'admin.orders.status': 'Status',
    'admin.orders.details': 'Details',
    'admin.orders.allStatuses': 'All Statuses',
    'admin.orders.searchPlaceholder': 'Search by order #, customer, or email...',

    // Order Statuses
    'admin.status.Pending': 'Pending',
    'admin.status.Confirmed': 'Confirmed',
    'admin.status.Processing': 'Processing',
    'admin.status.Shipped': 'Shipped',
    'admin.status.Delivered': 'Delivered',
    'admin.status.Cancelled': 'Cancelled',
    'admin.status.active': 'Active',
    'admin.status.inactive': 'Inactive',
    'admin.status.expired': 'Expired',
    'admin.status.approved': 'Approved',
    'admin.status.hidden': 'Hidden',
    'admin.status.pending': 'Pending',

    // Customers
    'admin.customers.title': 'Customers',
    'admin.customers.subtitle': 'Registered customer directory and order activity',
    'admin.customers.name': 'Name',
    'admin.customers.email': 'Email',
    'admin.customers.phone': 'Phone',
    'admin.customers.orders': 'Orders',
    'admin.customers.totalSpent': 'Total Spent',
    'admin.customers.registeredDate': 'Registered Date',
    'admin.customers.status': 'Status',
    'admin.customers.searchPlaceholder': 'Search customers by name or email...',

    // Users
    'admin.users.title': 'Users',
    'admin.users.subtitle': 'Manage user accounts and role permissions',
    'admin.users.name': 'Name',
    'admin.users.email': 'Email',
    'admin.users.role': 'Role',
    'admin.users.status': 'Status',
    'admin.users.createdDate': 'Created Date',
    'admin.users.roleCustomer': 'Customer',
    'admin.users.roleAdmin': 'Administrator',
    'admin.users.makeAdmin': 'Make Admin',
    'admin.users.revokeAdmin': 'Set Customer',
    'admin.users.activate': 'Activate',
    'admin.users.suspend': 'Suspend',

    // Inventory
    'admin.inventory.title': 'Inventory',
    'admin.inventory.subtitle': 'Monitor stock levels, reserved items, and low-stock thresholds',
    'admin.inventory.product': 'Product',
    'admin.inventory.sku': 'SKU',
    'admin.inventory.currentStock': 'Current Stock',
    'admin.inventory.reserved': 'Reserved',
    'admin.inventory.available': 'Available',
    'admin.inventory.threshold': 'Threshold',
    'admin.inventory.status': 'Status',
    'admin.inventory.inStock': 'In Stock',
    'admin.inventory.lowStock': 'Low Stock',
    'admin.inventory.outOfStock': 'Out of Stock',

    // Deals
    'admin.deals.title': 'Deals',
    'admin.deals.subtitle': 'Configure promotional discount campaigns',
    'admin.deals.add': 'Add Deal',
    'admin.deals.product': 'Product',
    'admin.deals.discountPercent': 'Discount Percentage',
    'admin.deals.startDate': 'Start Date',
    'admin.deals.endDate': 'End Date',
    'admin.deals.limitAmount': 'Limit Quantity',
    'admin.deals.active': 'Active',
    'admin.deals.expired': 'Expired',

    // Reviews
    'admin.reviews.title': 'Reviews',
    'admin.reviews.subtitle': 'Moderate and approve customer product reviews',
    'admin.reviews.customer': 'Customer',
    'admin.reviews.product': 'Product',
    'admin.reviews.rating': 'Rating',
    'admin.reviews.review': 'Review',
    'admin.reviews.date': 'Date',
    'admin.reviews.status': 'Status',
    'admin.reviews.approve': 'Approve',
    'admin.reviews.hide': 'Hide',
    'admin.reviews.delete': 'Delete',

    // Banners
    'admin.banners.title': 'Banners',
    'admin.banners.subtitle': 'Manage homepage promotional banners',
    'admin.banners.add': 'Add Banner',
    'admin.banners.headline': 'Headline',
    'admin.banners.subtext': 'Subtitle',
    'admin.banners.image': 'Image',
    'admin.banners.buttonText': 'Button Text',
    'admin.banners.buttonLink': 'Button Link',
    'admin.banners.startDate': 'Start Date',
    'admin.banners.endDate': 'End Date',
    'admin.banners.status': 'Status',

    // Analytics
    'admin.analytics.title': 'Analytics',
    'admin.analytics.subtitle': 'Store revenue, order trends, and top-selling smartphones',
    'admin.analytics.revenue': 'Revenue',
    'admin.analytics.orders': 'Orders',
    'admin.analytics.customers': 'Customers',
    'admin.analytics.productsSold': 'Products Sold',
    'admin.analytics.avgOrderValue': 'Average Order Value',
    'admin.analytics.topProducts': 'Best Selling Products',
    'admin.analytics.topBrands': 'Most Popular Brands',
    'admin.analytics.categorySales': 'Sales by Category',
    'admin.analytics.customerGrowth': 'Customer Growth',
    'admin.analytics.noData': 'No data available',

    // Notifications
    'admin.notifications.title': 'Notifications',
    'admin.notifications.subtitle': 'System alerts for new orders, low stock, customers, and reviews',
    'admin.notifications.newOrder': 'New Order',
    'admin.notifications.lowStock': 'Low Stock',
    'admin.notifications.outOfStock': 'Out of Stock',
    'admin.notifications.newCustomer': 'New Customer',
    'admin.notifications.newReview': 'New Review',
    'admin.notifications.markRead': 'Mark as Read',
    'admin.notifications.markAllRead': 'Mark All as Read',

    // Settings
    'admin.settings.title': 'Settings',
    'admin.settings.subtitle': 'Configure store identity, delivery rates, and security',
    'admin.settings.storeSettings': 'Store Settings',
    'admin.settings.adminProfile': 'Admin Profile',
    'admin.settings.security': 'Security',
    'admin.settings.notifications': 'Notifications',
    'admin.settings.deliverySettings': 'Delivery Settings',
    'admin.settings.orderSettings': 'Order Settings',
    'admin.settings.storeName': 'Store Name',
    'admin.settings.phone': 'Phone',
    'admin.settings.email': 'Email',
    'admin.settings.address': 'Address',
    'admin.settings.logo': 'Logo',
    'admin.settings.socialLinks': 'Social Networks',
    'admin.settings.standardDeliveryPrice': 'Standard Delivery Price',
    'admin.settings.expressDeliveryPrice': 'Express Delivery Price',
    'admin.settings.freeDeliveryThreshold': 'Free Delivery Threshold',

    // Empty / Error / Loading states
    'admin.state.loading': 'Loading data...',
    'admin.state.noProducts': 'No products found.',
    'admin.state.noOrders': 'No orders found.',
    'admin.state.noCustomers': 'No customers found.',
    'admin.state.noReviews': 'No reviews found.',
    'admin.state.noData': 'No data available yet.',
    'admin.state.error': 'An error occurred.',
    'admin.state.loadFailed': 'Failed to load data.',
    'admin.state.serverError': 'Server connection error.',
    'admin.state.tryAgain': 'Please try again.',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY = 'nova_mobile_lang';

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY) as Language | null;
      if (saved === 'UZ' || saved === 'RU' || saved === 'EN') {
        return saved;
      }
    } catch {
      // ignore storage errors
    }
    return 'UZ';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem(STORAGE_KEY, lang);
    } catch {
      // ignore storage errors
    }
  };

  useEffect(() => {
    document.documentElement.lang = language.toLowerCase();
  }, [language]);

  const t = (key: string, fallback?: string): string => {
    return translations[language]?.[key] ?? translations['UZ']?.[key] ?? fallback ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
